Bump version

diff --git a/k8s/k8s-ces-setup.yaml b/k8s/k8s-ces-setup.yaml
--- a/k8s/k8s-ces-setup.yaml
+++ b/k8s/k8s-ces-setup.yaml
@@ -41,7 +41,7 @@ spec:
     spec:
       containers:
         - name: k8s-ces-setup
-          image: "cloudogu/k8s-ces-setup:0.4.0"
+          image: "cloudogu/k8s-ces-setup:0.5.0"
           env:
             - name: GIN_MODE
               value: release
@@ -286,21 +286,7 @@ kind: ConfigMap
 metadata:
   name: k8s-ces-setup-cleanup-script
 data:
-  entrypoint.sh: |-
-    #!/bin/bash
-    STATE=$(kubectl get configmap k8s-setup-config -o jsonpath='{.data.state}');
-    if [[ ${STATE} == "installed" ]]; then 
-      kubectl delete configmap k8s-ces-setup-json || true
-      kubectl delete configmap k8s-setup-config || true
-      kubectl delete deployments,services,configmaps,secrets,roles,rolebindings,serviceaccounts -l app.kubernetes.io/name=k8s-ces-setup || true
-      kubectl patch cronjob cleanup -p '{"spec" : {"suspend" : true }}'
-      kubectl delete configmap k8s-ces-setup-cleanup-script
-      kubectl delete cronjob k8s-ces-setup-finisher
-      kubectl delete serviceaccount k8s-ces-setup-finisher
-      kubectl delete rolebinding k8s-ces-setup-finisher
-    else 
-      echo "setup seems not to be installed or successfully executed";
-    fi
+  entrypoint.sh: "#!/bin/bash\nSTATE=$(kubectl get configmap k8s-setup-config -o jsonpath='{.data.state}');\nif [[ ${STATE} == \"installed\" ]]; then \n  kubectl delete configmap k8s-ces-setup-json || true\n  kubectl delete configmap k8s-setup-config || true\n  kubectl delete deployments,services,configmaps,secrets,roles,rolebindings,serviceaccounts -l app.kubernetes.io/name=k8s-ces-setup || true\n  kubectl patch cronjob cleanup -p '{\"spec\" : {\"suspend\" : true }}'\n  kubectl delete configmap k8s-ces-setup-cleanup-script\n  kubectl delete cronjob k8s-ces-setup-finisher\n  kubectl delete serviceaccount k8s-ces-setup-finisher\n  kubectl delete rolebinding k8s-ces-setup-finisher\nelse \n  echo \"setup seems not to be installed or successfully executed\";\nfi"
 ---
 apiVersion: rbac.authorization.k8s.io/v1
 kind: Role
